[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }]

remappings = [
    'murky/=lib/murky',
    'forge-std=lib/forge-std/src',
    'foundry-devops/=lib/foundry-devops/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/'
]
